name: Release macOS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v0.1.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as prerelease'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cmake ninja vtk glfw

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..

    - name: Build
      run: |
        cd build
        ninja

    - name: Package
      run: |
        cd build
        cpack -G DragNDrop

    - name: List build artifacts
      run: |
        cd build
        ls -la *.dmg

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        prerelease: ${{ github.event.inputs.prerelease }}
        files: build/PowerImaginator-*.dmg
